MAP_FILENAME_PREFIX = "Africa"
MAX_ROUNDS = 6
MAP_DIRECTORY = "AfricaMaps"
INITIAL_MAP = MAP_DIRECTORY + "/" + "mmap.jpg"
AREA_DESCRIPTOR = "country"
HIGHLIGHT_COLOR = "yellow"
MAP_HEIGHT = 400
MAP_WIDTH = 800

score_to_state = {1: "Algeria",
                  2: "Angola",
                  3: "Benin (Dahomey)",
                  4: "Botswana",
                  5: "Burkina Faso (Republic of Upper Volta)",
                  6: "Burundi",
                  7: "Cameroon",
                  8: "Central African Republic",
                  9: "Chad (Tchad)",
                  10: "Cote d'Ivoire (Ivory Coast)",
                  11: "Democratic Republic of Congo (Congo-Kinshasa,Zaire)",
                  12: "Djibouti",
                  13: "Egypt (United Arab Republic)",
                  14: "Equatorial Guinea (Spanish Guinea)",
                  15: "Eritrea",
                  16: "Ethiopia",
                  17: "Gabon",
                  18: "Gambia",
                  19: "Ghana",
                  20: "Guinea (French Guinea)",
                  21: "Guinea-Bissau (Portuguese Guinea)",
                  22: "Kenya",
                  23: "Lesotho",
                  24: "Liberia",
                  25: "Libya",
                  26: "Madagascar (Malagasy Republic)",
                  27: "Malawi",
                  28: "Mali",
                  29: "Mauritania",
                  30: "Morocco",
                  31: "Mozambique",
                  32: "Namibia",
                  33: "Niger",
                  34: "Nigeria",
                  35: "Republic of Congo (Congo-Brazzaville)",
                  36: "Rwanda",
                  37: "Senegal",
                  38: "Sierra Leone (Salone)",
                  39: "Somalia",
                  40: "South Africa (R.S.A.)",
                  41: "South Sudan",
                  42: "Sudan",
                  43: "Swaziland (Eswatini)",
                  44: "Tanzania (German East Africa, Tanganyika, Zanzibar",
                  45: "Togo",
                  46: "Tunisia",
                  47: "Uganda",
                  48: "Western Sahara (Spanish Sahara)",
                  49: "Zambia",
                  50: "Zimbabwe (Southern Rhodesia)",
                  }