MAP_FILENAME_PREFIX = "Asia"
MAX_ROUNDS = 6
MAP_DIRECTORY = "AsiaMaps"
INITIAL_MAP = MAP_DIRECTORY + "/" + "mmap.jpg"
AREA_DESCRIPTOR = "country, city, island or sea"
HIGHLIGHT_COLOR = "yellow"
MAP_HEIGHT = 400
MAP_WIDTH = 800

score_to_state = {1: "Beijing",
                  2: "Busan",
                  3: "CHINA",
                  4: "Dalian",
                  5: "DMZ",
                  6: "EAST CHINA SEA",
                  7: "Fukuoka",
                  8: "Fukushima",
                  9: "Fuzhou",
                  10: "Guangzhou",
                  11: "GREAT WALL",
                  12: "Hangzhou",
                  13: "Hiroshima",
                  14: "HOKKAIDO",
                  15: "HONG KONG",
                  16: "HONSHU",
                  17: "Hososhima",
                  18: "Incheon",
                  19: "ISHIGAKI",
                  20: "JAPAN",
                  21: "JEJU",
                  22: "Jihxi",
                  23: "Keelung",
                  24: "Kaohsiung",
                  25: "Kyoto",
                  26: "KYUSHU",
                  27: "Linyi",
                  28: "LUZON",
                  29: "MACAO",
                  30: "Miyazaki",
                  31: "MONGOLIA",
                  32: "Nagasaki",
                  33: "Nagoya",
                  34: "NORTH KOREA",
                  35: "OKINAWA",
                  36: "Osaka",
                  37: "PACIFIC OCEAN",
                  38: "PHILIPPINES",
                  39: "Pyongyang",
                  40: "Qingdao",
                  41: "RUSSIA",
                  42: "Sapporo",
                  43: "SEA OF JAPAN",
                  44: "Sendai",
                  45: "Seoul",
                  46: "Shanghai",
                  47: "SHIKOKU",
                  48: "SOUTH CHINA SEA",
                  49: "SOUTH KOREA",
                  50: "Taipei",
                  51: "TAIWAN",
                  52: "Tianjin",
                  53: "Tokyo",
                  54: "Vladivostok",
                  55: "Wenzhou",
                  56: "Xiamen",
                  57: "Xian",
                  58: "Yantai",
                  59: "YELLOW SEA",
                  60: "Yokohama",
                  }