MAP_FILENAME_PREFIX = "China"
MAX_ROUNDS = 6
MAP_DIRECTORY = "ChinaMaps"
INITIAL_MAP = MAP_DIRECTORY + "/" + "mmap.jpg"
AREA_DESCRIPTOR = "province or provincial capital"
HIGHLIGHT_COLOR = "appears in print"
MAP_HEIGHT = 600
MAP_WIDTH = 700
BUTTON_HEIGHT = 2
BUTTON_WIDTH = 5

score_to_state = {1: "Anhui Province",
                  2: "Beijing Capital & Province (formerly known as Peking)",
                  3: "Changchun Capital of Jilin Province",
                  4: "Changsha Capital of Hunan Province",
                  5: "Chengdu Capital of Sichuan Province",
                  6: "Chongqing Capital & Province",
                  7: "Fujian Province",
                  8: "Fuzhou Capital of Fujian Province",
                  9: "Gansu Province",
                  10: "Guangdong Province",
                  11: "Guangxi Province",
                  12: "Guangzhou Capital of Guangdong Province (formerly known as Canton)",
                  13: "Guiyang Capital of Guizhou Province",
                  14: "Guizhou Province",
                  15: "Haikou Capital of Hainan Province",
                  16: "Hainan Province",
                  17: "Hangzhou Capital of Zhejiang Province",
                  18: "Harbin Capital of Heilongjiang Province",
                  19: "Hebei Province",
                  20: "Hefei Capital of Anhui Province",
                  21: "Heilongjiang Province",
                  22: "Henan Province",
                  23: "Hohhot Capital of Inner Mongolia",
                  24: "Hong Kong (former British colony)",
                  25: "Hubei Province",
                  26: "Hunan Province",
                  27: "Inner Mongolia Province",
                  28: "Jiangsu Province",
                  29: "Jiangxi Province",
                  30: "Jilin Province",
                  31: "Jinan Capital of Shandong Province",
                  32: "Kunming Capital of Yunnan Province",
                  33: "Lanzhou Capital of Gansu Province",
                  34: "Lhasa Capital of Tibet Province",
                  35: "Liaoning Province",
                  36: "Macao (former Portuguese colony)",
                  37: "Nanchang Capital of Jiangxi Province",
                  38: "Nanjing Capital of Jiangsu Province",
                  39: "Nanning Capital of Guangxi Province",
                  40: "Ningxia Province",
                  41: "Qinghai Province",
                  42: "Shandong Province",
                  43: "Shanghai Capital & Province",
                  44: "Shaanxi Province",
                  45: "Shanxi Province",
                  46: "Shenyang Capital of Liaoning Province",
                  47: "Shijiazhuang Capital of Hebei Province",
                  48: "Sichuan Province",
                  49: "Taipei Capital of Taiwan",
                  50: "Taiwan",
                  51: "Tianjin Capital & Province",
                  52: "Tiayuan Capital of Shanxi Province",
                  53: "Tibet Province",
                  54: "Urumqi Capital of Xinjiang Province",
                  55: "Wuhan Capital of Hubei Province",
                  56: "Xi'an Capital of Shaanxi Province",
                  57: "Xining Capital of Qinghai Province",
                  58: "Xinjiang Province",
                  59: "Yinchuan Capital of Ningxia Province",
                  60: "Yunnan Province",
                  61: "Zheijiang Province",
                  62: "Zhengzhou Capital of Henan Province"
                  }

