MAP_FILENAME_PREFIX = "GR"
MAX_ROUNDS = 7
MAP_DIRECTORY = "GRMaps"
INITIAL_MAP = MAP_DIRECTORY + "/" + "mmap.jpg"
AREA_DESCRIPTOR = "cities, islands or seas"
HIGHLIGHT_COLOR = "yellow"
MAP_HEIGHT = 400
MAP_WIDTH = 800

score_to_state = {1: "Adiparos",
                  2: "Aegean Sea",
                  3: "Agios Efstratios",
                  4: "Aigina",
                  5: "Alexandroupolis",
                  6: "Alonnisos",
                  7: "Amfissa",
                  8: "Amorgos",
                  9: "Anafi",
                  10: "Andros",
                  11: "Antikythira",
                  12: "Areopolis",
                  13: "Argostolion",
                  14: "Arta",
                  15: "Astypalaia",
                  16: "Athens",
                  17: "Chalki",
                  18: "Chalkida",
                  19: "Chania",
                  20: "Chios",
                  21: "Corfu",
                  22: "Corinth",
                  23: "Crete",
                  24: "Cyclades",
                  25: "Dilos",
                  26: "Dodecanese Islands",
                  27: "Drama",
                  28: "Edessa",
                  29: "Ermoupolis",
                  30: "Evvoia",
                  31: "Florina",
                  32: "Folegandros",
                  33: "Gavdos",
                  34: "Gioura",
                  35: "Grevena",
                  36: "Gulf of Corinth",
                  37: "Igoumenitsa",
                  38: "Ikaria",
                  39: "Ioannina",
                  40: "Ionian Sea",
                  41: "Irakleion",
                  42: "Kalamata",
                  43: "Kalymnos",
                  44: "Karditsa",
                  45: "Karpathos",
                  46: "Karpenision",
                  47: "Kasos",
                  48: "Kastoria",
                  49: "Katerini",
                  50: "Kavala",
                  51: "Kea",
                  52: "Kefallinia",
                  53: "Kerkyra",
                  54: "Kilkis",
                  55: "Kimolos",
                  56: "Kissamos",
                  57: "Komotini",
                  58: "Kos",
                  59: "Kozani",
                  60: "Kyra Panagia",
                  61: "Kythira",
                  62: "Kythnos",
                  63: "Lamia",
                  64: "Larisa",
                  65: "Lavrion",
                  66: "Lefkada",
                  67: "Levadeia",
                  68: "Leros",
                  69: "Lesvos",
                  70: "Limnos",
                  71: "Los",
                  72: "Mediterranean Sea",
                  73: "Mesolongion",
                  74: "Milos",
                  75: "Mykonos",
                  76: "Mytilini",
                  77: "Nafplio",
                  78: "Naxos",
                  79: "Nissiros",
                  80: "Northern Sporades",
                  81: "Paros",
                  82: "Patmos",
                  83: "Patrai",
                  84: "Piraeus",
                  85: "Polygyros",
                  86: "Poros",
                  87: "Preveza",
                  88: "Psara",
                  89: "Pyrgos",
                  90: "Rethymnon",
                  91: "Rhodes",
                  92: "Rodes",
                  93: "Samos",
                  94: "Samothraki",
                  95: "Sea of Crete",
                  96: "Serifos",
                  97: "Serres",
                  98: "Sifnos",
                  99: "Sikinos",
                  100: "Siteia",
                  101: "Skiathos",
                  102: "Skopelos",
                  103: "Skyros",
                  104: "Sparta",
                  105: "Spetses",
                  106: "Symi",
                  107: "Thasos",
                  108: "Thermaikos Kolpos",
                  109: "Thessaloniki",
                  110: "Thrakikon Pelagos",
                  111: "Thira / Santorini",
                  112: "Tilos",
                  113: "Tino",
                  114: "Trikala",
                  115: "Tripolis",
                  116: "Veroia",
                  117: "Volos",
                  118: "Xanthi",
                  119: "Ydra",
                  120: "Zaknythos",
                  }